### ISSUE TITLE
原生之类的挺需要国内的位置服务

### ISSUE THREAD

**Issue by lizhenglin2002** [Magisk-Modules-Repo/OnePlusOxygenOSBACKChinaWeather#2]

**Comment by user1121114685** [comment]
高德位置服务我在用miui国际版的时候修改过，需要修改底层，比较麻烦的事情。所以我觉得需要空闲时间来看看！搞一个东西需要大量时间。

**Comment by lizhenglin2002** [comment]
> 高德位置服务我在用MIUI国际版的时候修改过，需要修改底层，比较麻烦的事情。所以我觉得需要空闲时间来看看！搞一个东西需要大量时间。

如果修改成功了，在其他类原生的可以使用吗？

**Comment by user1121114685** [comment]
不可以，每个系统都不一样。这个涉及底层不能乱尝试。有可能导致无法开机或者无限崩溃，卸载之后也可能不会恢复。

**Comment by user1121114685** [comment]
但是类原生都有修改教程的。你可以尝试
